# Generated by Django 5.2.2 on 2025-08-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stid', models.IntegerField(unique=True)),
                ('name_prefix', models.CharField(choices=[('นาย.', 'นาย.'), ('นาง.', 'นาง.'), ('นางสาว.', 'นางสาว.')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
    ]
